### ISSUE TITLE
"No URL's to Crawl" message

### ISSUE THREAD

**Issue by mtndan** [FCC/Crawler#1]
Hi, I'm playing with the tool and have followed instructions for configuration, but when I visit the crawl.php page I get the message "No URL's to Crawl". Am I missing something?

Thanks in advance,

**Comment by gregelin** [comment]
Geezh, Mtndan -- I have not been checking this repo. My apologies for not getting back to you. 

The crawler looks to the database to get URLs. You need to seed your database with a URL.  From the README:

```
2. (for now) in phpMyAdmin insert the seed URL into the urls table.
    * URL should be something like: www.fcc.gov
    * URL should have a trailing slash
    * (for now) May also want to set clicks to '0' to avoid problems 
```

You will need to insert a URL, like "www.mysite.com/" or "www.mysite.com/page.html" into the `urls` table.  When you start the crawler, the crawler will look at the `urls` table, take the first one, and start crawling.

For each URL (page) the crawler finds, it will first pull out all the URLs in the page and add each URL to the `urls` table to track new URLs that need to be crawled. Duplicate URLs are not added.

**Comment by gregelin** [comment]
Feel free to improve the admin interface to make it easier to get started and send me a pull request.

**Comment by ghost** [comment]
I followed this instruction too , and I guess @mtndan did too . but it says the same "No URLs to crawl!"
any guide ?
